version: '3'

services:
  postgres:
    image: "postgres"
    environment:
      - "POSTGRES_USER=test"
      - "POSTGRES_DB=test"
      - "POSTGRES_PASSWORD=test"
    expose:
      - "5432"
    ports:
      - "5432:5432"